#!/usr/bin/env bash
# Regenerate the vicinae theme files from the THEMES table in set-theme.sh.
# Palettes are read out of Ghostty's own theme files so vicinae matches the
# terminal exactly, instead of becoming a second hand-maintained copy.
set -euo pipefail

THEME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SET_THEME="$THEME_DIR/set-theme.sh"
GHOSTTY_THEMES="/Applications/Ghostty.app/Contents/Resources/ghostty/themes"
OUT_DIR="$THEME_DIR/../vicinae/themes"

[ -d "$GHOSTTY_THEMES" ] || {
  echo "Ghostty themes not found at $GHOSTTY_THEMES" >&2
  exit 1
}
mkdir -p "$OUT_DIR"

# Weighted blend of two #rrggbb colors; w is the weight of $2, in percent.
blend() {
  local a="${1#\#}" b="${2#\#}" w="$3" out="#" i ca cb
  for i in 0 2 4; do
    ca=$((16#${a:$i:2}))
    cb=$((16#${b:$i:2}))
    out="$out$(printf '%02x' $(((ca * (100 - w) + cb * w) / 100)))"
  done
  echo "$out"
}

count=0
while IFS='|' read -r key label ghostty_name _mode _tuicr _value; do
  [ -n "$key" ] || continue
  src="$GHOSTTY_THEMES/$ghostty_name"
  [ -f "$src" ] || {
    echo "skip $key: no ghostty theme '$ghostty_name'" >&2
    continue
  }

  p=()
  bg=""
  fg=""
  while IFS= read -r line; do
    line="${line// /}"
    case "$line" in
      palette=*)
        entry="${line#palette=}"
        p[${entry%%=*}]="${entry#*=}"
        ;;
      background=*) bg="${line#background=}" ;;
      foreground=*) fg="${line#foreground=}" ;;
    esac
  done <"$src"
  bg="#${bg#\#}"
  fg="#${fg#\#}"

  # secondary_background sits just under the window background; border takes the
  # bright-black slot pulled most of the way back toward bg so it reads as a
  # hairline rather than a stripe.
  secondary=$(blend "$bg" "#000000" 25)
  border=$(blend "$bg" "${p[8]}" 45)
  # The 16-color palette has no orange slot, so mix the red and yellow ones.
  orange=$(blend "${p[1]}" "${p[3]}" 50)

  cat >"$OUT_DIR/$key.toml" <<EOF
# Generated by gen-vicinae-themes.sh from Ghostty's "$ghostty_name" - do not edit by hand.
[meta]
version = 1
name = "$label"
description = "$label, matched to the ghostty/tmux/nvim theme of the same name."
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
background = "$bg"
foreground = "$fg"
secondary_background = "$secondary"
border = "$border"
accent = "${p[4]}"
accent_foreground = "$bg"

[colors.accents]
red = "${p[1]}"
green = "${p[2]}"
yellow = "${p[3]}"
blue = "${p[4]}"
purple = "${p[5]}"
cyan = "${p[6]}"
magenta = "${p[13]}"
orange = "$orange"

[colors.text]
muted = "${p[8]}"
danger = "colors.accents.red"
success = "colors.accents.green"
EOF
  count=$((count + 1))
done < <(sed -n '/^THEMES="$/,/^"$/p' "$SET_THEME" | sed '1d;$d' | sed '/^$/d')

echo "wrote $count themes to $OUT_DIR"
